package br.com.intelipost.domain.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model for the User_Details table.
 * 
 * @author rnojiri
 */
public class UserDetails implements Serializable
{
	private static final long serialVersionUID = 1651143160152237020L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.id_user
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Long idUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.nam_first
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private String namFirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.nam_last
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private String namLast;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.enu_sex
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Sex enuSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.flg_allow_emails
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Boolean flgAllowEmails;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.dat_birth
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Date datBirth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User_Details.dat_creation
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Date datCreation;

	public UserDetails()
	{

	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.id_user
	 * 
	 * @return the value of User_Details.id_user
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Long getIdUser()
	{
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.id_user
	 * 
	 * @param idUser
	 *            the value for User_Details.id_user
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setIdUser(Long idUser)
	{
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.nam_first
	 * 
	 * @return the value of User_Details.nam_first
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public String getNamFirst()
	{
		return namFirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.nam_first
	 * 
	 * @param namFirst
	 *            the value for User_Details.nam_first
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setNamFirst(String namFirst)
	{
		this.namFirst = namFirst == null ? null : namFirst.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.nam_last
	 * 
	 * @return the value of User_Details.nam_last
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public String getNamLast()
	{
		return namLast;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.nam_last
	 * 
	 * @param namLast
	 *            the value for User_Details.nam_last
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setNamLast(String namLast)
	{
		this.namLast = namLast == null ? null : namLast.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.enu_sex
	 * 
	 * @return the value of User_Details.enu_sex
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Sex getEnuSex()
	{
		return enuSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.enu_sex
	 * 
	 * @param enuSex
	 *            the value for User_Details.enu_sex
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setEnuSex(Sex enuSex)
	{
		this.enuSex = enuSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.flg_allow_emails
	 * 
	 * @return the value of User_Details.flg_allow_emails
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Boolean getFlgAllowEmails()
	{
		return flgAllowEmails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.flg_allow_emails
	 * 
	 * @param flgAllowEmails
	 *            the value for User_Details.flg_allow_emails
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setFlgAllowEmails(Boolean flgAllowEmails)
	{
		this.flgAllowEmails = flgAllowEmails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.dat_birth
	 * 
	 * @return the value of User_Details.dat_birth
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Date getDatBirth()
	{
		return datBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.dat_birth
	 * 
	 * @param datBirth
	 *            the value for User_Details.dat_birth
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setDatBirth(Date datBirth)
	{
		this.datBirth = datBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User_Details.dat_creation
	 * 
	 * @return the value of User_Details.dat_creation
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Date getDatCreation()
	{
		return datCreation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User_Details.dat_creation
	 * 
	 * @param datCreation
	 *            the value for User_Details.dat_creation
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setDatCreation(Date datCreation)
	{
		this.datCreation = datCreation;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((datBirth == null) ? 0 : datBirth.hashCode());
		result = prime * result + ((datCreation == null) ? 0 : datCreation.hashCode());
		result = prime * result + ((enuSex == null) ? 0 : enuSex.hashCode());
		result = prime * result + ((flgAllowEmails == null) ? 0 : flgAllowEmails.hashCode());
		result = prime * result + ((idUser == null) ? 0 : idUser.hashCode());
		result = prime * result + ((namFirst == null) ? 0 : namFirst.hashCode());
		result = prime * result + ((namLast == null) ? 0 : namLast.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		UserDetails other = (UserDetails) obj;
		if (datBirth == null)
		{
			if (other.datBirth != null) return false;
		}
		else if (!datBirth.equals(other.datBirth)) return false;
		if (datCreation == null)
		{
			if (other.datCreation != null) return false;
		}
		else if (!datCreation.equals(other.datCreation)) return false;
		if (enuSex != other.enuSex) return false;
		if (flgAllowEmails == null)
		{
			if (other.flgAllowEmails != null) return false;
		}
		else if (!flgAllowEmails.equals(other.flgAllowEmails)) return false;
		if (idUser == null)
		{
			if (other.idUser != null) return false;
		}
		else if (!idUser.equals(other.idUser)) return false;
		if (namFirst == null)
		{
			if (other.namFirst != null) return false;
		}
		else if (!namFirst.equals(other.namFirst)) return false;
		if (namLast == null)
		{
			if (other.namLast != null) return false;
		}
		else if (!namLast.equals(other.namLast)) return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "UserDetails [idUser=" + idUser + ", namFirst=" + namFirst + ", namLast=" + namLast + ", enuSex=" + enuSex + ", flgAllowEmails=" + flgAllowEmails
				+ ", datBirth=" + datBirth + ", datCreation=" + datCreation + "]";
	}

}
