package br.com.intelipost.domain.model;

import java.io.Serializable;

/**
 * Model for the User table.
 * 
 * @author rnojiri
 */
public class User implements Serializable
{
	private static final long serialVersionUID = -3513544651982037534L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.id_user
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Long idUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.eml_user
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private String emlUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.cod_password
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private String codPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.flg_active
	 * 
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	private Boolean flgActive;

	public User()
	{

	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.id_user
	 * 
	 * @return the value of User.id_user
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Long getIdUser()
	{
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.id_user
	 * 
	 * @param idUser
	 *            the value for User.id_user
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setIdUser(Long idUser)
	{
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.eml_user
	 * 
	 * @return the value of User.eml_user
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public String getEmlUser()
	{
		return emlUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.eml_user
	 * 
	 * @param emlUser
	 *            the value for User.eml_user
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setEmlUser(String emlUser)
	{
		this.emlUser = emlUser == null ? null : emlUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.cod_password
	 * 
	 * @return the value of User.cod_password
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public String getCodPassword()
	{
		return codPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.cod_password
	 * 
	 * @param codPassword
	 *            the value for User.cod_password
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setCodPassword(String codPassword)
	{
		this.codPassword = codPassword == null ? null : codPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.flg_active
	 * 
	 * @return the value of User.flg_active
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public Boolean getFlgActive()
	{
		return flgActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.flg_active
	 * 
	 * @param flgActive
	 *            the value for User.flg_active
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	public void setFlgActive(Boolean flgActive)
	{
		this.flgActive = flgActive;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codPassword == null) ? 0 : codPassword.hashCode());
		result = prime * result + ((emlUser == null) ? 0 : emlUser.hashCode());
		result = prime * result + ((flgActive == null) ? 0 : flgActive.hashCode());
		result = prime * result + ((idUser == null) ? 0 : idUser.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		User other = (User) obj;
		if (codPassword == null)
		{
			if (other.codPassword != null) return false;
		}
		else if (!codPassword.equals(other.codPassword)) return false;
		if (emlUser == null)
		{
			if (other.emlUser != null) return false;
		}
		else if (!emlUser.equals(other.emlUser)) return false;
		if (flgActive == null)
		{
			if (other.flgActive != null) return false;
		}
		else if (!flgActive.equals(other.flgActive)) return false;
		if (idUser == null)
		{
			if (other.idUser != null) return false;
		}
		else if (!idUser.equals(other.idUser)) return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "User [idUser=" + idUser + ", emlUser=" + emlUser + ", codPassword=" + codPassword + ", flgActive=" + flgActive + "]";
	}
}
