package br.com.intelipost.domain.persistence;

import br.com.intelipost.domain.model.UserDetails;

/**
 * User_Details table mapper interface.
 * 
 * @author rnojiri
 */
public interface UserDetailsMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User_Details
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	int deleteByPrimaryKey(Long idUser);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User_Details
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	int insert(UserDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User_Details
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	UserDetails selectByPrimaryKey(Long idUser);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User_Details
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	int updateByPrimaryKey(UserDetails record);
}