package br.com.intelipost.domain.persistence;

import org.apache.ibatis.annotations.Param;

import br.com.intelipost.domain.model.User;

/**
 * User table mapper interface.
 * 
 * @author rnojiri
 */
public interface UserMapper
{
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	int deleteByPrimaryKey(Long idUser);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	User selectByPrimaryKey(Long idUser);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 *
	 * @mbg.generated Sun Mar 05 18:33:41 BRT 2017
	 */
	int updateByPrimaryKey(User record);
	
	/**
	 * Selects by user e-mail.
	 * 
	 * @param emlUser
	 * @return User
	 */
	User selectByEmail(@Param("emlUser") String emlUser);
}